#!/bin/bash
#
# /etc/update-motd.d/00-header
# Banner + welcome line (hostname)

CYAN="\033[36m"
BOLD="\033[1m"
RESET="\033[0m"

HOSTNAME=$(hostname)

echo -e "${CYAN}"
cat << "EOF"
       ____  ____    _______    _   __   __    ____  ____  _   ________  _________   _______
      / / / / / /   /  _/   |  / | / /  / /   / __ \/ __ \/ | / /_  __/ / / ____/ | / / ___/
 __  / / / / / /    / // /| | /  |/ /  / /   / / / / / / /  |/ / / /_  / / __/ /  |/ /\__ \ 
/ /_/ / /_/ / /____/ // ___ |/ /|  /  / /___/ /_/ / /_/ / /|  / / / /_/ / /___/ /|  /___/ / 
\____/\____/_____/___/_/  |_/_/ |_/  /_____/\____/\____/_/ |_/ /_/\____/_____/_/ |_//____/ 
EOF

echo -e "${RESET}${BOLD}"
echo -e "Welcome to ${CYAN}${HOSTNAME}${RESET}${BOLD} ($(uname -o) $(uname -r) $(uname -m))${RESET}\n"